Traceback (most recent call last):
  File "/Users/bm/Desktop/kabupicks/auto_update.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
